language: java

# Configure mail notifications
notifications:
  email:
    on_success: never
    on_failure: always

# Use fast containers
sudo: false

matrix:
  include:
   # Headed Linux
    - os: linux
      dist: trusty
      jdk: oraclejdk9

    # Headless Linux
    - os: linux
      dist: trusty
      jdk: oraclejdk9
      env:
        - _JAVA_OPTIONS="-Djava.awt.headless=true -Dtestfx.robot=glass -Dtestfx.headless=true -Dprism.order=sw -Dprism.text=t2k -Dtestfx.setup.timeout=2500"

install: true

before_install:
# Update permission for gradle wrapper
  - chmod +x gradlew
# for headless testing
  - if [[ "${TRAVIS_OS_NAME}" == linux ]]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi


# Run code coverage report
script:
  - ./gradlew build
  - ./gradlew codeCoverageReport

cache: false

# Upload test coverage to codecov
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Generate project object model (POM)
before_deploy:
  - ./gradlew generatePomFileForMavenCustomPublication

# Deploy artefact to bintray (https://docs.travis-ci.com/user/deployment/bintray)
deploy:
  provider: bintray
  on:
    all_branches: true
  file: ./bintray.json
  user: mwieland
  key:
    secure: N/9uOVFj7NQOuP0cathx/IK/jYxij9yLpZ75fwyB5qvDNc1z7pZ2k5saYouBTMmhG7czkFCzdTJ8U8bbZHT4ZgMlhc2meHm1zpIAw/F8nHVaE1DxHqt+4SymQoANps/vOM2lyHmYUF2LA26A4Xni/dY0UVQ7xPVUYNMgLyrAtA66PvPA/xWEnExo6IGOZSQicPHAp+2YDL865igpFTYCvTwpoT/UlVL8xYp4MDr5/02WHLHLmobcIl/mspYKwT7zrhYGM4ONtcrZaq5kQpJjXQP/bCygGIufjGtOQOYnR5wAo7pwV4mZwP6UIzIERBGksI3l9qk2V5Ft50xbEaD6JsltMxM00//D1rs8tuAQNwVUTZigCcpue3FCzn9WNAllXQbjHsvdr+mFkGYIH7/4pwXd+pt1DF4e0Kqq/YEO46aIV2cen0LT3h74ZFHM93kwMxb2cOBRYVMK8hm9qwqmeWqNUIRXJeREAIy2qGA610i9B/+zFMOHv9B6A99kqDLAm7LE912oi0wfpzUetbVMa/d0bnO+qU/QrpbZmTl8xs3YWOMw4aieDVQC+Ub22Hb39av6dujADYKi1CcB57mQbqJ3nWuvRHcBBQPqXRq990W2Hr2H0id/UCDd3dZ+kgdJKqvFg61mQfCkqTQrL2ANlwge2CDKvPbD95YC3iECt2w=
  skip_cleanup: true
  passphrase: GPG_PASSPHRASE